### ISSUE TITLE
Proposal Feedback:

### ISSUE THREAD

**Issue by aespaldi** [noltron000/graphs-project#1]
Proposal 4/4 

Context and solutions look good.  Make sure you have some resources / an approach to solving the 2D / 3D component.

**Comment by noltron000** [comment]
note: 3D was a typo, but it'd be interesting to tackle that problem in the future. It would not be too difficult to make this or even higher dimension models, linking north/south/east/west/upward/downward/forward/backward for 4th dimension, and so forth. Each vertex would ultimately just need more neighbors.

At any rate, primary features were to include:
- maze generation
- maze solver
- maze graphic creator (creating a traditional look took longer to create, and is actually using an interesting graph structure in of itself.)
- maze scrambler (creates `n` random, new neighbors to destroy tree-like structures)
